version: "3.8"

services:
  server:
    build: ./server  # Dockerfile inside "server" directory
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    build: ./database
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - mynetwork

networks:
  mynetwork:  # Custom network for communication
    driver: bridge

volumes:
  pg_data: