name: Deploy and Test Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      - name: Start Docker Compose services
        run: docker compose up -d --build

      - name: Wait for services to be ready
        run: |
          echo "Waiting for services to start..."
          sleep 10  # Adjust if needed
          docker ps -a

      - name: Run tests inside the server container
        run: docker exec $(docker-compose ps -q server) pytest  # Change to your test command

      - name: Stop and clean up Docker Compose
        run: docker compose down
