name: Deploy and Test Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
    AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
    ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
    ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
    DOCKER_IMAGE_NAME_API: 'api'
    DOCKERFILE_PATH_API: './server'
    DOCKER_IMAGE_NAME_DB: 'db'
    DOCKERFILE_PATH_DB: './database'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start Docker Compose services
        run: docker compose up -d --build

      - name: Wait for services to be ready
        run: |
          echo "Waiting for services to start..."
          sleep 10  # Adjust if needed
          docker ps -a

      - name: Run tests inside the server container
        run: docker exec $(docker ps -q --filter "name=server") pytest

      - name: Stop and clean up Docker Compose
        run: docker compose down

  build-server-image:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Azure Container Registry
        run: |
          docker login ${{ env.AZURE_CONTAINER_REGISTRY }} -u ${{ env.ACR_USERNAME }} -p ${{ env.ACR_PASSWORD }}

      - name: Build and push image
        run: |
          docker build \
            --progress=plain \
            --no-cache \
            ${{ env.DOCKERFILE_PATH_API }} \
            -t ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME_API }}:latest
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME_API }}:latest

  build-db-image:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Azure Container Registry
        run: |
          docker login ${{ env.AZURE_CONTAINER_REGISTRY }} -u ${{ env.ACR_USERNAME }} -p ${{ env.ACR_PASSWORD }}

      - name: Build and push image
        run: |
          docker build \
            --progress=plain \
            --no-cache \
            ${{ env.DOCKERFILE_PATH_DB }} \
            -t ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME_DB }}:latest
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME_DB }}:latest
    